# Generated by Django 2.2.6 on 2019-10-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='email',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
