# Generated by Django 2.2.6 on 2019-10-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usersprofile',
            name='modified_by',
        ),
    ]
