# Generated by Django 2.2.6 on 2019-10-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191021_0915'),
    ]

    operations = [

    ]
