# Generated by Django 2.2.6 on 2019-10-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='created_at',
        ),
    ]
